version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lightlist-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lightlist_db
      POSTGRES_USER: lightlist_user
      POSTGRES_PASSWORD: lightlist_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lightlist_user -d lightlist_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-test:
    image: postgres:15
    container_name: lightlist-db-test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: lightlist_test_db
      POSTGRES_USER: lightlist_user
      POSTGRES_PASSWORD: lightlist_password
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lightlist_user -d lightlist_test_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data: