set shell := ["zsh", "-cu"]

build:
  DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer  xcodegen generate
  DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcodebuild -skipPackagePluginValidation -project Lightlist.xcodeproj -scheme Lightlist -configuration Debug -derivedDataPath build -destination 'generic/platform=iOS Simulator' CODE_SIGN_IDENTITY="-" build

build-release:
  DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcodegen generate
  DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcodebuild -skipPackagePluginValidation -project Lightlist.xcodeproj -scheme Lightlist -configuration Release -derivedDataPath build-release -destination 'generic/platform=iOS Simulator' CODE_SIGN_IDENTITY="-" build

archive:
  DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcodegen generate
  DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcodebuild -skipPackagePluginValidation -project Lightlist.xcodeproj -scheme Lightlist -configuration Release -destination 'generic/platform=iOS' -archivePath build-archive/Lightlist.xcarchive -allowProvisioningUpdates DEVELOPMENT_TEAM="{{env_var('LIGHTLIST_IOS_TEAM_ID')}}" CODE_SIGN_STYLE=Automatic archive
  DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcodebuild -exportArchive -archivePath build-archive/Lightlist.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build-archive/export -allowProvisioningUpdates

run:
  xcrun simctl install booted build/Build/Products/Debug-iphonesimulator/Lightlist.app
  xcrun simctl launch booted com.lightlist.app

simulator-list:
  xcrun simctl list devices available

simulator target='':
  open -a Simulator
  xcrun simctl boot "{{target}}"
  xcrun simctl bootstatus "{{target}}" -b

screenshot target='current':
  xcrun simctl io booted screenshot ios_{{target}}.png
